version: 0.2
env:
  variables:
    TERRAFORM_VERSION: 1.2.8
  exported-variables:
    - build_id
    - build_tag
    - pipeline_region

phases:
  install:
    commands:
      - echo "Installing terraform..."
      - cd /usr/bin
      - curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - terraform --version
      - echo "Completed installing terraform..."
  build:
    commands:
      - echo "Terraform plan for ${TEAM}/${ENV} in REGION=${REGION}"
      - cd "${CODEBUILD_SRC_DIR}/examples/lb-service"
      - echo "terraform init -backend-config="key=${TEAM}/${ENV}/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="bucket=${TF_BACKEND_CONFIG_PREFIX}-${ENV}" -backend-config="dynamodb_table=${TF_BACKEND_CONFIG_PREFIX}-lock-${ENV}" -backend-config="encrypt=true""
      - terraform init -backend-config="key=${TEAM}/${ENV}/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="bucket=${TF_BACKEND_CONFIG_PREFIX}-${ENV}" -backend-config="dynamodb_table=${TF_BACKEND_CONFIG_PREFIX}-lock-${ENV}" -backend-config="encrypt=true"
      - terraform fmt
      - terraform validate -no-color
      - echo "terraform plan -var-file "terraform.tfvars.example" -var "repository_owner=aws-ia" -out=tfplan"
      - terraform plan -var-file "terraform.tfvars.example" -var "repository_owner=aws-ia" -out=tfplan -compact-warnings

  post_build:
    commands:
      - echo "[Post Build]:Completed terraform plan..."
artifacts:
  files:
    - '**/*'